### ISSUE TITLE
過剰売却ルール

### ISSUE THREAD

**Issue by atsfour** [rev84/NationalEconomySolo#7]
http://spa-game.com/?p=4557

このルールに対応する。

**Comment by rev84** [comment]
過剰売却ルールは、説明書に書かれていないので、テクスト論的には対応の必要がないといえばないですね。
また、現行でも、プレイヤーがそう意図すれば、過剰売却ルールでプレイできるということも、実装の重要性を下げています。

しかし、設計者の意図であることや、ユーザがいちいち気を払わなくてもよいようにすることでゲーム性が向上する可能性があることなどから、実装してもいいように思います。

私が実装するかは微妙なところです。

**Comment by atsfour** [comment]
ありがとうございます。

私としては、「お金が足りているのに建物を売ることはできません」（pp.11下部）の記述の意図がこれであると感じています。

ソロだと過剰に売ることが利益になる場面（前ターンで売った重要建物を労働者配置ごとの使用不能からガードするなど）もちょくちょくある気がします。

とりあえず実装は済んでいましたので #12 に入れました。
